apiVersion: v1
kind: Pod
metadata:
  namespace: composer
spec:
  containers:
    - command: ['/bin/sh', '-c']
      args:
        - |
          cp {WIZINK_REWARDS_FILE_PATH} {WIZINK_SFTP_OUTPUT_FILE_PATH}
          sshpass -e sftp -o BatchMode=no -b - -o StrictHostKeyChecking=no {SFTP_USER}@{SFTP_HOST} <<EOF
          put {WIZINK_SFTP_OUTPUT_FILE_PATH} {SFTP_TO_PATH}
          EOF
      env:
        - name: SSHPASS
          valueFrom:
            secretKeyRef:
              key: test-pass
              name: wizink
      image: chartedcode/alpine-sftp-client
      name: base
      resources:
        limits:
          cpu: "1"
          memory: 512Mi
      volumeMounts:
        - mountPath: {DATA_PREFIX}
          name: data
  restartPolicy: Never
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: {PVC_DATA_NAME}
