---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: clickhouse-copier
spec:
  template:
    spec:
      containers:
        - command:
            - clickhouse-copier
            - "--config-file=${CH_COPIER_CONFIG}"
            - "--task-path=${CH_COPIER_TASKPATH}"
            - "--task-file=${CH_COPIER_TASKFILE}"
            - "--base-dir=${CH_COPIER_BASEDIR}"
          env:
            - name: CH_COPIER_CONFIG
              value: "/var/lib/clickhouse/tmp/zookeeper.xml"
            - name: CH_COPIER_TASKPATH
              value: "/clickhouse/copier/tasks/task01"
            - name: CH_COPIER_TASKFILE
              value: "/var/lib/clickhouse/tmp/task01.yaml"
            - name: CH_COPIER_BASEDIR
              value: "/var/lib/clickhouse/tmp"
          image: clickhouse/clickhouse-server:21.8
          name: clickhouse-copier
          resources:
            limits:
              cpu: "1"
              memory: 2048Mi
          volumeMounts:
            - mountPath: /var/lib/clickhouse/tmp
              name: copier-config
      volumes:
        - name: copier-config
          configMap:
            name: copier-config
      restartPolicy: Never
  backoffLimit: 4
