---
apiVersion: v1
kind: ConfigMap
metadata:
  name: task-config
  namespace: xxxxxxx
data:
  task-config.yaml: |
    <clickhouse>
        <logger>
            <level>trace</level>
            <size>100M</size>
            <count>3</count>
        </logger>
        <remote_servers>
            <cluster_01>
                <shard>
                    <replica>
                        <host>clickhouse-01</host>
                        <port>9000</port>
                    </replica>
                    <replica>
                        <host>clickhouse-02</host>
                        <port>9000</port>
                    </replica>
                </shard>
            </cluster_01>
            <cluster_02>
                <!-- <secret></secret> -->
                <shard>
                    <replica>
                        <host>clickhouse-03</host>
                        <port>9000</port>
                    </replica>
                </shard>
                <shard>
                    <replica>
                        <host>clickhouse-04</host>
                        <port>9000</port>
                    </replica>
                </shard>
            </cluster_02>
        </remote_servers>
        <max_workers>1</max_workers>
        <settings_pull>
            <readonly>1</readonly>
        </settings_pull>
        <settings_push>
            <readonly>0</readonly>
        </settings_push>
        <settings>
            <connect_timeout>3</connect_timeout>
            <insert_distributed_sync>1</insert_distributed_sync>
        </settings>
        <tables>
            <table_ventas>
                <cluster_pull>cluster_01</cluster_pull>
                <database_pull>default</database_pull>
                <table_pull>fact_venta_evento</table_pull>
                <cluster_push>cluster_02</cluster_push>
                <database_push>default</database_push>
                <table_push>fact_venta_evento</table_push>
                <engine>
                    Engine=ReplicatedMergeTree('/clickhouse/{cluster}/tables/{shard}/fact_venta_evento', '{replica}')
                    PARTITION BY toYYYYMM(fecha_hora_pedido)
                    ORDER BY (id_cadena, id_producto)
                    SETTINGS index_granularity = 8192
                </engine>
                <sharding_key>rand()</sharding_key>
            </table_ventas>
        </tables>
      </clickhouse>
