---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
  namespace: xxxxxxxx
data:
  zookeeper.xml: |
    <clickhouse>
      <logger>
          <level>trace</level>
          <size>100M</size>
          <count>3</count>
      </logger>
      <zookeeper>
            <node>
                <host>zoo1</host>
                <port>2181</port>
            </node>
            <node>
                <host>zoo2</host>
                <port>2181</port>
            </node>
            <node>
                <host>zoo3</host>
                <port>2181</port>
            </node>
      </zookeeper>
    </clickhouse>