---
version: "3"

services:
  clickhouse_copier:
    container_name: clickhouse_copier
    image: clickhouse/clickhouse-server:21.8
    volumes:
      - ./configs:/var/lib/clickhouse/tmp
    # command: ['clickhouse-copier', '--daemon', '--basedir=/tmp', '--port', '8123']
    command:
      - clickhouse-copier
      - "--config-file=${CH_COPIER_CONFIG}"
      - "--task-path=${CH_COPIER_TASKPATH}"
      - "--task-file=${CH_COPIER_TASKFILE}"
      - --status
      #- --task-upload-force
      - "--base-dir=${CH_COPIER_BASEDIR}"
    networks:
      - default

networks:
  default:
    external: true
